// <auto-generated />
using LinearSistemas.CanaisVendas.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LinearSistemas.CanaisVendas.Infra.Migrations
{
    [DbContext(typeof(VendasContext))]
    partial class VendasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LinearSistemas.CanaisVendas.Domain.Models.CanalVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("CanaisVendas");
                });

            modelBuilder.Entity("LinearSistemas.CanaisVendas.Domain.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("Descricao");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("LinearSistemas.CanaisVendas.Domain.Models.ProdutoCanalVenda", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("ProdutoId");

                    b.Property<int>("CanalVendaId")
                        .HasColumnType("int")
                        .HasColumnName("CanalVendaId");

                    b.HasKey("ProdutoId", "CanalVendaId");

                    b.HasIndex("CanalVendaId");

                    b.ToTable("ProdutoCanaisVendas");
                });

            modelBuilder.Entity("LinearSistemas.CanaisVendas.Domain.Models.ProdutoCanalVenda", b =>
                {
                    b.HasOne("LinearSistemas.CanaisVendas.Domain.Models.CanalVenda", "CanalVenda")
                        .WithMany("CanaisVendas")
                        .HasForeignKey("CanalVendaId")
                        .IsRequired();

                    b.HasOne("LinearSistemas.CanaisVendas.Domain.Models.Produto", "Produto")
                        .WithMany("CanaisVendas")
                        .HasForeignKey("ProdutoId")
                        .IsRequired();

                    b.Navigation("CanalVenda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LinearSistemas.CanaisVendas.Domain.Models.CanalVenda", b =>
                {
                    b.Navigation("CanaisVendas");
                });

            modelBuilder.Entity("LinearSistemas.CanaisVendas.Domain.Models.Produto", b =>
                {
                    b.Navigation("CanaisVendas");
                });
#pragma warning restore 612, 618
        }
    }
}
